<?php
/**
 * aaPanel Installation Script for Flussonic Dashboard
 * This script provides a GUI interface for installing the application on aaPanel hosting
 */

// Check if running on aaPanel
if (!isset($_SERVER['SERVER_SOFTWARE']) || strpos($_SERVER['SERVER_SOFTWARE'], 'aaPanel') === false) {
    die('This installation script is designed specifically for aaPanel hosting environment.');
}

// Installation configuration
define('INSTALL_DIR', __DIR__);
define('CONFIG_FILE', INSTALL_DIR . '/config.php');
define('LOCK_FILE', INSTALL_DIR . '/.installed');

// Check if already installed
if (file_exists(LOCK_FILE)) {
    die('Application is already installed. Please remove .installed file to reinstall.');
}

// Database configuration
$db_config = [
    'host' => 'localhost',
    'port' => 3306,
    'name' => '',
    'user' => '',
    'pass' => ''
];

// Application configuration
$app_config = [
    'backend_domain' => '',
    'frontend_domain' => '',
    'python_version' => '3.10',
    'secret_key' => bin2hex(random_bytes(32))
];

// Handle form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $db_config['name'] = $_POST['db_name'] ?? '';
    $db_config['user'] = $_POST['db_user'] ?? '';
    $db_config['pass'] = $_POST['db_pass'] ?? '';
    $db_config['host'] = $_POST['db_host'] ?? 'localhost';
    $db_config['port'] = $_POST['db_port'] ?? 3306;
    
    $app_config['backend_domain'] = $_POST['backend_domain'] ?? '';
    $app_config['frontend_domain'] = $_POST['frontend_domain'] ?? '';
    $app_config['python_version'] = $_POST['python_version'] ?? '3.10';
    
    // Validate inputs
    $errors = [];
    if (empty($db_config['name'])) $errors[] = 'Database name is required';
    if (empty($db_config['user'])) $errors[] = 'Database username is required';
    if (empty($db_config['pass'])) $errors[] = 'Database password is required';
    if (empty($app_config['backend_domain'])) $errors[] = 'Backend domain is required';
    if (empty($app_config['frontend_domain'])) $errors[] = 'Frontend domain is required';
    
    if (empty($errors)) {
        // Test database connection
        try {
            $dsn = "mysql:host={$db_config['host']};port={$db_config['port']};dbname={$db_config['name']}";
            $pdo = new PDO($dsn, $db_config['user'], $db_config['pass']);
            $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
            
            // Create installation lock file
            file_put_contents(LOCK_FILE, date('Y-m-d H:i:s'));
            
            // Create configuration file
            $config_content = "<?php\n";
            $config_content .= "// Configuration file generated by installer\n";
            $config_content .= "return [\n";
            $config_content .= "    'database' => [\n";
            $config_content .= "        'host' => '{$db_config['host']}',\n";
            $config_content .= "        'port' => {$db_config['port']},\n";
            $config_content .= "        'name' => '{$db_config['name']}',\n";
            $config_content .= "        'user' => '{$db_config['user']}',\n";
            $config_content .= "        'pass' => '{$db_config['pass']}'\n";
            $config_content .= "    ],\n";
            $config_content .= "    'app' => [\n";
            $config_content .= "        'backend_domain' => '{$app_config['backend_domain']}',\n";
            $config_content .= "        'frontend_domain' => '{$app_config['frontend_domain']}',\n";
            $config_content .= "        'python_version' => '{$app_config['python_version']}',\n";
            $config_content .= "        'secret_key' => '{$app_config['secret_key']}'\n";
            $config_content .= "    ]\n";
            $config_content .= "];\n";
            
            file_put_contents(CONFIG_FILE, $config_content);
            
            // Create .env file for backend
            $env_content = "DATABASE_URL=mysql+mysqlconnector://{$db_config['user']}:{$db_config['pass']}@{$db_config['host']}:{$db_config['port']}/{$db_config['name']}\n";
            $env_content .= "SECRET_KEY={$app_config['secret_key']}\n";
            $env_content .= "DEBUG=False\n";
            $env_content .= "CORS_ORIGINS=https://{$app_config['frontend_domain']}\n";
            
            file_put_contents('.env', $env_content);
            
            $success = true;
        } catch (PDOException $e) {
            $errors[] = 'Database connection failed: ' . $e->getMessage();
        }
    }
}
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Flussonic Dashboard - aaPanel Installation</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            background-color: #f5f5f5;
            margin: 0;
            padding: 20px;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            background: white;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 {
            color: #333;
            text-align: center;
            margin-bottom: 30px;
        }
        .form-group {
            margin-bottom: 20px;
        }
        label {
            display: block;
            margin-bottom: 5px;
            font-weight: 600;
            color: #555;
        }
        input[type="text"], input[type="password"], input[type="number"] {
            width: 100%;
            padding: 10px;
            border: 1px solid #ddd;
            border-radius: 4px;
            font-size: 14px;
            box-sizing: border-box;
        }
        .error {
            background-color: #fee;
            color: #c33;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        .success {
            background-color: #efe;
            color: #3c3;
            padding: 10px;
            border-radius: 4px;
            margin-bottom: 20px;
        }
        button {
            background-color: #007cba;
            color: white;
            padding: 12px 24px;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            font-size: 16px;
            width: 100%;
        }
        button:hover {
            background-color: #005a87;
        }
        .section {
            margin-bottom: 30px;
        }
        .section h2 {
            color: #007cba;
            border-bottom: 2px solid #007cba;
            padding-bottom: 5px;
            margin-bottom: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Flussonic Dashboard Installation</h1>
        
        <?php if (isset($success) && $success): ?>
            <div class="success">
                <h3>Installation Complete!</h3>
                <p>Your application has been successfully configured. Please follow these steps:</p>
                <ol>
                    <li>Create a Python project in aaPanel with domain: <strong><?php echo htmlspecialchars($app_config['backend_domain']); ?></strong></li>
                    <li>Set project path to: <strong>/www/wwwroot/<?php echo htmlspecialchars($app_config['backend_domain']); ?></strong></li>
                    <li>Select Python version: <strong><?php echo htmlspecialchars($app_config['python_version']); ?></strong></li>
                    <li>Set startup file to: <strong>backend/main.py</strong></li>
                    <li>Set startup function to: <strong>app</strong></li>
                    <li>Create frontend site in aaPanel with domain: <strong><?php echo htmlspecialchars($app_config['frontend_domain']); ?></strong></li>
                    <li>Copy contents of <strong>frontend/dist</strong> to <strong>/www/wwwroot/<?php echo htmlspecialchars($app_config['frontend_domain']); ?></strong></li>
                    <li>Setup cron job to run <strong>backend/app/services/usage_collector.py</strong> every hour</li>
                </ol>
                <p><strong>Important:</strong> Make sure to restart the Python project after configuration.</p>
            </div>
        <?php else: ?>
            <?php if (!empty($errors)): ?>
                <div class="error">
                    <h3>Errors:</h3>
                    <ul>
                        <?php foreach ($errors as $error): ?>
                            <li><?php echo htmlspecialchars($error); ?></li>
                        <?php endforeach; ?>
                    </ul>
                </div>
            <?php endif; ?>
            
            <form method="POST">
                <div class="section">
                    <h2>Database Configuration</h2>
                    <div class="form-group">
                        <label for="db_host">Database Host:</label>
                        <input type="text" id="db_host" name="db_host" value="<?php echo htmlspecialchars($db_config['host']); ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="db_port">Database Port:</label>
                        <input type="number" id="db_port" name="db_port" value="<?php echo htmlspecialchars($db_config['port']); ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="db_name">Database Name:</label>
                        <input type="text" id="db_name" name="db_name" value="<?php echo htmlspecialchars($db_config['name']); ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="db_user">Database Username:</label>
                        <input type="text" id="db_user" name="db_user" value="<?php echo htmlspecialchars($db_config['user']); ?>" required>
                    </div>
                    <div class="form-group">
                        <label for="db_pass">Database Password:</label>
                        <input type="password" id="db_pass" name="db_pass" value="<?php echo htmlspecialchars($db_config['pass']); ?>" required>
                    </div>
                </div>
                
                <div class="section">
                    <h2>Application Configuration</h2>
                    <div class="form-group">
                        <label for="backend_domain">Backend Domain:</label>
                        <input type="text" id="backend_domain" name="backend_domain" value="<?php echo htmlspecialchars($app_config['backend_domain']); ?>" placeholder="api.yourdomain.com" required>
                    </div>
                    <div class="form-group">
                        <label for="frontend_domain">Frontend Domain:</label>
                        <input type="text" id="frontend_domain" name="frontend_domain" value="<?php echo htmlspecialchars($app_config['frontend_domain']); ?>" placeholder="dashboard.yourdomain.com" required>
                    </div>
                    <div class="form-group">
                        <label for="python_version">Python Version:</label>
                        <input type="text" id="python_version" name="python_version" value="<?php echo htmlspecialchars($app_config['python_version']); ?>" required>
                    </div>
                </div>
                
                <button type="submit">Install Application</button>
            </form>
        <?php endif; ?>
    </div>
</body>
</html>
